{% set version = "0.3.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-config
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/config_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/config/config_{{ version }}.tar.gz
  sha256: 7b5c21c2b86d5ba88d6e888bc614d5633f4fb5c0b50bb498a529c32ccf931065

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-yaml >=2.1.13
  run:
    - r-base
    - r-yaml >=2.1.13

test:
  commands:
    - $R -e "library('config')"           # [not win]
    - "\"%R%\" -e \"library('config')\""  # [win]

about:
  home: https://github.com/rstudio/config
  license: GPL-3.0-only
  summary: Manage configuration values across multiple environments (e.g. development, test, production). Read values using a function that determines the current environment and returns the appropriate value.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
