appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: MYgjSrxYKESUdDOurWMsohAqrCOr7jq616A0S3D7bfsKj5LYqWh2LC/pvh4MlzM/+keqcJMc9v4r9/+YM/D9eNcvbEjzPRNcfWwzP1T1gQ8cgyY4GlSIfjplsUor4Jf2D0zWzYr1xeuTPReCvNRlUUhG5IisKRTHGaI9jU8FrJoXvE8EaHH8X55k8Yvy9Gk/8+ZEwTkKd2u9cotMNVNPpi2ePU7Yo8lPsCHDaAVbuh3PD6+OuEedQpJ17/gcvPC5SCovbra79I9tBwxu8ku7NxCjclSoJ1PZALlo7H26rHM+e8TohhS4FIGPigRUR/Vu5Y2wzzMae5VKtmg3VxZrcl2u2y0eiVUZeolZq4L1oA2p3AG+yr87NNGtC/W61dhdsxSRiQd+/VB117eMe98jIxB/294j6/5ZqqxwpBACDceOmzU8x38WtxomvDMxuCw9vmIrFN3w+Fm6PJnvFD3GGnrPwldu+b2GyxKJcYENDnTHW18GKFv0mK+L2WJ7OuFjoWQJrBUbNlkn7LyHpbdHxxkK0eN04f0QE/y/WTsbUjGBSYnL0C3E6Bs+sUrompmr01vypnIUwFbt3GLKDHN8XQL58C3qUeb+9o3YZPke+3519MxkLbFDPLCeET/RLbYsTJke3eLVwYHFO3R0qbnae+BewQXPFCt8FnbB9h56n/8=}
